test :: ()
{
    plugin :: Plugin.{
                       init = init,
                       shutdown = shutdown,
                       run = run,
                       stop = stop,
                       wait_for_stopped = wait_for_stopped,
                       pre_reload = pre_reload,
                       post_reload = post_reload,
                       get_sync_data = get_sync_data };

    print( "", asd, asd,
           asd, asd, asd, asd,
           asd, asd, asd, asdh, test( a, b,
                                      c, d ), qwe,
           we, qwe );

    a := int.[ 1, 2, 3, 4,
               5, 6, 7, 8, 9 ];

    a := asd.{
               asdasd,
               asd };

    testaaaaaaa( asd, asd.{ a,
                            g }, a,
                 f, g );

    a := Struct.{ 1, 2, 3,
                  4, 5,
                  6, 7 };

    a := int.[ 1, 2, 3,
               4, 5,
               6, 7 ];
}
