b := ifx a 
else 6;

if a > b {
    print("true");
} 
else {
    print("false");
}

if a then b += a; else c *= a;
if a b += a; else c *= a;
if a 

    b; 
else 
    c;


if a     b; 
else c;

#run {
    a: int = 3;
    if a == {
        case 1;
            b := 3;
        case 2;
            b := 4;
        case 3;
            b := 5;
        case;
    }
    print("%", a);
}

for things print(it);
for things 
    print(it);

for things {print(it);}
for things 
{print(it);}

while true print("true");
while true 
    print("true");

while true {print("true");}
while true {
    print("true");
    print("true");
    print("true");
    print("true");
    }

if a > b{
    print("true");
}
else {
    print("false");
    print("false");
}
